//! Session Memory Service — automatic conversation memory extraction and storage.
//!
//! Maintains a markdown file with notes about the current conversation.
//! Runs periodically in the background to extract key information
//! without interrupting the main conversation flow.
//!
//! # Architecture
//!
//! - [`SessionMemoryStore`] — in-memory + on-disk memory storage
//! - [`MemoryEntry`] — a single memory entry (key, value, timestamp, source)
//! - [`SessionMemoryConfig`] — configuration for extraction thresholds
//! - [`extract_memories()`] — extracts memories from conversation text
//! - [`load_session_memory()`] — loads session memory from storage

use std::collections::BTreeMap;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::Result;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Default minimum context window tokens before initializing session memory.
const DEFAULT_MIN_TOKENS_TO_INIT: u64 = 10_000;

/// Default minimum token growth between updates.
const DEFAULT_MIN_TOKENS_BETWEEN_UPDATE: u64 = 5_000;

/// Default number of tool calls between updates.
const DEFAULT_TOOL_CALLS_BETWEEN_UPDATES: u32 = 3;

/// Default extraction wait timeout in milliseconds.
#[allow(dead_code)]
const EXTRACTION_WAIT_TIMEOUT_MS: u64 = 15_000;

/// Default extraction stale threshold in milliseconds.
const EXTRACTION_STALE_THRESHOLD_MS: u64 = 60_000;

/// Configuration for session memory extraction thresholds.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionMemoryConfig {
    /// Minimum context window tokens before initializing session memory.
    pub minimum_message_tokens_to_init: u64,
    /// Minimum context window growth (in tokens) between updates.
    pub minimum_tokens_between_update: u64,
    /// Number of tool calls between session memory updates.
    pub tool_calls_between_updates: u32,
}

impl Default for SessionMemoryConfig {
    fn default() -> Self {
        Self {
            minimum_message_tokens_to_init: DEFAULT_MIN_TOKENS_TO_INIT,
            minimum_tokens_between_update: DEFAULT_MIN_TOKENS_BETWEEN_UPDATE,
            tool_calls_between_updates: DEFAULT_TOOL_CALLS_BETWEEN_UPDATES,
        }
    }
}

impl SessionMemoryConfig {
    /// Creates a new config with custom thresholds.
    #[must_use]
    pub fn new(
        min_tokens_to_init: u64,
        min_tokens_between_update: u64,
        tool_calls_between_updates: u32,
    ) -> Self {
        Self {
            minimum_message_tokens_to_init: min_tokens_to_init,
            minimum_tokens_between_update: min_tokens_between_update,
            tool_calls_between_updates,
        }
    }
}

// ---------------------------------------------------------------------------
// Memory Entry
// ---------------------------------------------------------------------------

/// Source of a memory entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[derive(Default)]
#[serde(rename_all = "snake_case")]
pub enum MemorySource {
    /// Extracted automatically from conversation.
    #[default]
    AutoExtraction,
    /// Manually added by the user.
    Manual,
    /// Loaded from a previous session.
    PreviousSession,
    /// Generated by a sub-agent.
    SubAgent,
}


/// A single memory entry in the session memory store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    /// Unique key for this memory.
    pub key: String,
    /// The memory value / content.
    pub value: String,
    /// When this memory was created (epoch millis).
    pub timestamp: u64,
    /// Source of this memory.
    pub source: MemorySource,
    /// Optional category for grouping.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Relevance score (0.0–1.0) for ranking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub relevance: Option<f64>,
}

impl MemoryEntry {
    /// Creates a new memory entry with the current timestamp.
    #[must_use]
    pub fn new(key: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            value: value.into(),
            timestamp: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map_or(0, |d| d.as_millis() as u64),
            source: MemorySource::AutoExtraction,
            category: None,
            relevance: None,
        }
    }

    /// Creates a new memory entry with a specific source.
    #[must_use]
    pub fn with_source(
        key: impl Into<String>,
        value: impl Into<String>,
        source: MemorySource,
    ) -> Self {
        Self {
            source,
            ..Self::new(key, value)
        }
    }

    /// Creates a manually added memory entry.
    #[must_use]
    pub fn manual(key: impl Into<String>, value: impl Into<String>) -> Self {
        Self::with_source(key, value, MemorySource::Manual)
    }

    /// Sets the category for this entry.
    #[must_use]
    pub fn with_category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    /// Sets the relevance score for this entry.
    #[must_use]
    pub fn with_relevance(mut self, score: f64) -> Self {
        self.relevance = Some(score.clamp(0.0, 1.0));
        self
    }

    /// Returns whether this entry is expired relative to the given TTL.
    #[must_use]
    pub fn is_expired(&self, ttl_ms: u64, now_ms: u64) -> bool {
        if ttl_ms == 0 {
            return false;
        }
        now_ms.saturating_sub(self.timestamp) > ttl_ms
    }
}

// ---------------------------------------------------------------------------
// Session Memory Store
// ---------------------------------------------------------------------------

/// In-memory session memory storage with extraction state tracking.
pub struct SessionMemoryStore {
    /// Memory entries indexed by key.
    entries: BTreeMap<String, MemoryEntry>,
    /// Configuration.
    config: SessionMemoryConfig,
    /// Whether session memory has been initialized.
    initialized: bool,
    /// Token count at last extraction.
    tokens_at_last_extraction: u64,
    /// Whether extraction is currently in progress.
    extraction_in_progress: bool,
    /// Timestamp when extraction started.
    extraction_started_at: Option<u64>,
    /// Total tool calls since last extraction.
    tool_calls_since_last_extraction: u32,
    /// Last summarized message ID.
    last_summarized_message_id: Option<String>,
}

impl Default for SessionMemoryStore {
    fn default() -> Self {
        Self::new(SessionMemoryConfig::default())
    }
}

impl SessionMemoryStore {
    /// Creates a new session memory store with the given configuration.
    #[must_use]
    pub fn new(config: SessionMemoryConfig) -> Self {
        Self {
            entries: BTreeMap::new(),
            config,
            initialized: false,
            tokens_at_last_extraction: 0,
            extraction_in_progress: false,
            extraction_started_at: None,
            tool_calls_since_last_extraction: 0,
            last_summarized_message_id: None,
        }
    }

    /// Returns whether session memory has been initialized.
    #[must_use]
    pub fn is_initialized(&self) -> bool {
        self.initialized
    }

    /// Marks session memory as initialized.
    pub fn mark_initialized(&mut self) {
        self.initialized = true;
    }

    /// Checks if the initialization threshold has been met.
    #[must_use]
    pub fn has_met_initialization_threshold(&self, current_token_count: u64) -> bool {
        current_token_count >= self.config.minimum_message_tokens_to_init
    }

    /// Checks if the update threshold has been met.
    #[must_use]
    pub fn has_met_update_threshold(&self, current_token_count: u64) -> bool {
        let growth = current_token_count.saturating_sub(self.tokens_at_last_extraction);
        growth >= self.config.minimum_tokens_between_update
    }

    /// Records the token count at extraction time.
    pub fn record_extraction_token_count(&mut self, count: u64) {
        self.tokens_at_last_extraction = count;
    }

    /// Increments the tool call counter.
    pub fn record_tool_call(&mut self) {
        self.tool_calls_since_last_extraction += 1;
    }

    /// Returns whether the tool call threshold has been met.
    #[must_use]
    pub fn has_met_tool_call_threshold(&self) -> bool {
        self.tool_calls_since_last_extraction >= self.config.tool_calls_between_updates
    }

    /// Resets the tool call counter after extraction.
    pub fn reset_tool_call_counter(&mut self) {
        self.tool_calls_since_last_extraction = 0;
    }

    /// Marks extraction as started.
    pub fn mark_extraction_started(&mut self) {
        self.extraction_in_progress = true;
        self.extraction_started_at = Some(
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map_or(0, |d| d.as_millis() as u64),
        );
    }

    /// Marks extraction as completed.
    pub fn mark_extraction_completed(&mut self) {
        self.extraction_in_progress = false;
        self.extraction_started_at = None;
    }

    /// Returns whether extraction is currently in progress.
    #[must_use]
    pub fn is_extraction_in_progress(&self) -> bool {
        self.extraction_in_progress
    }

    /// Checks if the current extraction is stale (> 1 minute old).
    #[must_use]
    pub fn is_extraction_stale(&self) -> bool {
        match self.extraction_started_at {
            Some(started) => {
                let now = SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .map_or(0, |d| d.as_millis() as u64);
                now.saturating_sub(started) > EXTRACTION_STALE_THRESHOLD_MS
            }
            None => false,
        }
    }

    /// Determines whether memory extraction should happen.
    #[must_use]
    pub fn should_extract_memory(
        &mut self,
        current_token_count: u64,
        has_tool_calls_in_last_turn: bool,
    ) -> bool {
        // Check initialization threshold
        if !self.initialized {
            if !self.has_met_initialization_threshold(current_token_count) {
                return false;
            }
            self.mark_initialized();
        }

        // Check update thresholds
        let has_met_token_threshold = self.has_met_update_threshold(current_token_count);
        let has_met_tool_call_threshold = self.has_met_tool_call_threshold();

        let should_extract = (!has_tool_calls_in_last_turn || has_met_tool_call_threshold)
            && has_met_token_threshold;

        if should_extract {
            self.record_extraction_token_count(current_token_count);
            self.reset_tool_call_counter();
        }

        should_extract
    }

    /// Adds a memory entry.
    pub fn add_entry(&mut self, entry: MemoryEntry) {
        self.entries.insert(entry.key.clone(), entry);
    }

    /// Removes a memory entry by key.
    pub fn remove_entry(&mut self, key: &str) -> Option<MemoryEntry> {
        self.entries.remove(key)
    }

    /// Gets a memory entry by key.
    #[must_use]
    pub fn get_entry(&self, key: &str) -> Option<&MemoryEntry> {
        self.entries.get(key)
    }

    /// Returns all memory entries.
    #[must_use]
    pub fn entries(&self) -> &BTreeMap<String, MemoryEntry> {
        &self.entries
    }

    /// Returns the number of memory entries.
    #[must_use]
    pub fn entry_count(&self) -> usize {
        self.entries.len()
    }

    /// Clears all memory entries.
    pub fn clear(&mut self) {
        self.entries.clear();
    }

    /// Sets the last summarized message ID.
    pub fn set_last_summarized_message_id(&mut self, id: impl Into<String>) {
        self.last_summarized_message_id = Some(id.into());
    }

    /// Returns the last summarized message ID.
    #[must_use]
    pub fn last_summarized_message_id(&self) -> Option<&str> {
        self.last_summarized_message_id.as_deref()
    }

    /// Returns the memory content as a markdown string.
    #[must_use]
    pub fn to_markdown(&self) -> String {
        if self.entries.is_empty() {
            return String::new();
        }

        let mut md = String::from("# Session Memory\n\n");

        // Group by category
        let mut categories: BTreeMap<Option<&str>, Vec<&MemoryEntry>> = BTreeMap::new();
        for entry in self.entries.values() {
            categories
                .entry(entry.category.as_deref())
                .or_default()
                .push(entry);
        }

        for (category, entries) in &categories {
            if let Some(cat) = category {
                md.push_str(&format!("## {cat}\n\n"));
            }
            for entry in entries {
                md.push_str(&format!("- **{}**: {}\n", entry.key, entry.value));
            }
            md.push('\n');
        }

        md
    }

    /// Resets all state (for testing).
    pub fn reset(&mut self) {
        self.entries.clear();
        self.initialized = false;
        self.tokens_at_last_extraction = 0;
        self.extraction_in_progress = false;
        self.extraction_started_at = None;
        self.tool_calls_since_last_extraction = 0;
        self.last_summarized_message_id = None;
    }

    /// Returns a reference to the config.
    #[must_use]
    pub fn config(&self) -> &SessionMemoryConfig {
        &self.config
    }
}

// ---------------------------------------------------------------------------
// Memory Extraction
// ---------------------------------------------------------------------------

/// A simplified conversation message for memory extraction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationMessage {
    /// Message role (user, assistant, system).
    pub role: String,
    /// Message text content.
    pub content: String,
    /// Whether this message contains tool calls.
    pub has_tool_calls: bool,
}

impl ConversationMessage {
    /// Creates a new conversation message.
    #[must_use]
    pub fn new(role: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: role.into(),
            content: content.into(),
            has_tool_calls: false,
        }
    }

    /// Creates a message with tool calls flag.
    #[must_use]
    pub fn with_tool_calls(role: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            has_tool_calls: true,
            ..Self::new(role, content)
        }
    }
}

/// Extracts memories from a list of conversation messages.
///
/// Uses heuristic rules to identify key information:
/// - User's stated goals and tasks
/// - Important decisions and preferences
/// - File paths and code references
/// - Error patterns and solutions
///
/// Returns a list of extracted memory entries.
pub fn extract_memories(messages: &[ConversationMessage]) -> Vec<MemoryEntry> {
    let mut entries = Vec::new();

    for msg in messages {
        if msg.role != "user" {
            continue;
        }

        let content = msg.content.trim();
        if content.is_empty() {
            continue;
        }

        // Extract task/goal statements
        extract_goals(content, &mut entries);

        // Extract file references
        extract_file_references(content, &mut entries);

        // Extract preferences
        extract_preferences(content, &mut entries);
    }

    // Deduplicate by key
    let mut seen = std::collections::HashSet::new();
    entries.retain(|e| seen.insert(e.key.clone()));

    entries
}

/// Extracts goal/task statements from user messages.
fn extract_goals(content: &str, entries: &mut Vec<MemoryEntry>) {
    let goal_patterns = [
        ("i want to ", "goal"),
        ("i need to ", "goal"),
        ("help me ", "goal"),
        ("build ", "task"),
        ("implement ", "task"),
        ("fix ", "task"),
        ("create ", "task"),
        ("add ", "task"),
        ("refactor ", "task"),
    ];

    let lower = content.to_lowercase();
    for (pattern, category) in &goal_patterns {
        if lower.contains(pattern) {
            // Extract the sentence containing the pattern
            if let Some(sentence) = content.split('.').find(|s| s.to_lowercase().contains(pattern))
            {
                let trimmed = sentence.trim();
                if !trimmed.is_empty() && trimmed.len() < 200 {
                    entries.push(
                        MemoryEntry::new(format!("goal_{}", entries.len()), trimmed)
                            .with_category(category.to_string()),
                    );
                }
            }
            break; // One goal per message
        }
    }
}

/// Extracts file path references from messages.
fn extract_file_references(content: &str, entries: &mut Vec<MemoryEntry>) {
    // Simple heuristic: look for common file extensions
    let extensions = [
        ".rs", ".ts", ".js", ".py", ".toml", ".json", ".yaml", ".yml", ".md",
    ];

    for word in content.split_whitespace() {
        let cleaned = word.trim_matches(|c: char| c == '`' || c == '"' || c == '\'' || c == ',');
        if extensions.iter().any(|ext| cleaned.ends_with(ext)) && cleaned.len() < 100 {
            entries.push(
                MemoryEntry::new(format!("file_{}", cleaned.replace('.', "_")), cleaned)
                    .with_category("file_reference"),
            );
        }
    }
}

/// Extracts user preferences from messages.
fn extract_preferences(content: &str, entries: &mut Vec<MemoryEntry>) {
    let pref_patterns = [
        ("i prefer ", "preference"),
        ("use ", "preference"),
        ("don't use ", "preference"),
        ("always ", "preference"),
        ("never ", "preference"),
    ];

    let lower = content.to_lowercase();
    for (pattern, category) in &pref_patterns {
        if lower.contains(pattern) {
            if let Some(sentence) = content.split('.').find(|s| s.to_lowercase().contains(pattern))
            {
                let trimmed = sentence.trim();
                if !trimmed.is_empty() && trimmed.len() < 200 {
                    entries.push(
                        MemoryEntry::new(format!("pref_{}", entries.len()), trimmed)
                            .with_category(category.to_string()),
                    );
                }
            }
            break;
        }
    }
}

/// Loads session memory from a markdown string.
/// Parses the markdown format produced by [`SessionMemoryStore::to_markdown`].
pub fn load_session_memory(markdown: &str) -> Result<SessionMemoryStore> {
    let mut store = SessionMemoryStore::default();

    if markdown.trim().is_empty() {
        return Ok(store);
    }

    let mut current_category: Option<String> = None;

    for line in markdown.lines() {
        let trimmed = line.trim();

        // Category headers
        if let Some(stripped) = trimmed.strip_prefix("## ") {
            current_category = Some(stripped.trim().to_string());
            continue;
        }

        // Skip top-level header
        if trimmed.starts_with("# ") {
            continue;
        }

        // List items: - **key**: value
        if trimmed.starts_with("- **")
            && let Some(rest) = trimmed.strip_prefix("- **")
            && let Some(end_idx) = rest.find("**: ")
        {
            let key = &rest[..end_idx];
            let value = &rest[end_idx + 4..];
            let mut entry = MemoryEntry::new(key, value);
            if let Some(cat) = &current_category {
                entry = entry.with_category(cat.clone());
            }
            store.add_entry(entry);
        }
    }

    store.mark_initialized();
    Ok(store)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- SessionMemoryConfig tests ---

    #[test]
    fn test_config_default() {
        let config = SessionMemoryConfig::default();
        assert_eq!(config.minimum_message_tokens_to_init, 10_000);
        assert_eq!(config.minimum_tokens_between_update, 5_000);
        assert_eq!(config.tool_calls_between_updates, 3);
    }

    #[test]
    fn test_config_custom() {
        let config = SessionMemoryConfig::new(5_000, 2_000, 5);
        assert_eq!(config.minimum_message_tokens_to_init, 5_000);
        assert_eq!(config.minimum_tokens_between_update, 2_000);
        assert_eq!(config.tool_calls_between_updates, 5);
    }

    #[test]
    fn test_config_serialization() {
        let config = SessionMemoryConfig::default();
        let json = serde_json::to_string(&config).expect("serialize");
        let deserialized: SessionMemoryConfig =
            serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deserialized.minimum_message_tokens_to_init, 10_000);
    }

    // --- MemoryEntry tests ---

    #[test]
    fn test_entry_new() {
        let entry = MemoryEntry::new("test_key", "test value");
        assert_eq!(entry.key, "test_key");
        assert_eq!(entry.value, "test value");
        assert_eq!(entry.source, MemorySource::AutoExtraction);
        assert!(entry.timestamp > 0);
    }

    #[test]
    fn test_entry_manual() {
        let entry = MemoryEntry::manual("pref", "Use tabs");
        assert_eq!(entry.source, MemorySource::Manual);
    }

    #[test]
    fn test_entry_with_category() {
        let entry = MemoryEntry::new("k", "v").with_category("goals");
        assert_eq!(entry.category, Some("goals".to_string()));
    }

    #[test]
    fn test_entry_with_relevance() {
        let entry = MemoryEntry::new("k", "v").with_relevance(0.8);
        assert_eq!(entry.relevance, Some(0.8));
    }

    #[test]
    fn test_entry_relevance_clamped() {
        let entry = MemoryEntry::new("k", "v").with_relevance(1.5);
        assert_eq!(entry.relevance, Some(1.0));
    }

    #[test]
    fn test_entry_not_expired() {
        let entry = MemoryEntry::new("k", "v");
        let now = entry.timestamp;
        assert!(!entry.is_expired(60_000, now));
    }

    #[test]
    fn test_entry_expired() {
        let mut entry = MemoryEntry::new("k", "v");
        entry.timestamp = 1_000_000;
        assert!(entry.is_expired(60_000, 2_000_000));
    }

    #[test]
    fn test_entry_zero_ttl_never_expires() {
        let mut entry = MemoryEntry::new("k", "v");
        entry.timestamp = 0;
        assert!(!entry.is_expired(0, u64::MAX));
    }

    // --- SessionMemoryStore tests ---

    #[test]
    fn test_store_new() {
        let store = SessionMemoryStore::default();
        assert!(!store.is_initialized());
        assert_eq!(store.entry_count(), 0);
    }

    #[test]
    fn test_store_add_and_get_entry() {
        let mut store = SessionMemoryStore::default();
        store.add_entry(MemoryEntry::new("key1", "value1"));
        assert_eq!(store.entry_count(), 1);
        assert_eq!(store.get_entry("key1").expect("entry").value, "value1");
    }

    #[test]
    fn test_store_remove_entry() {
        let mut store = SessionMemoryStore::default();
        store.add_entry(MemoryEntry::new("key1", "value1"));
        let removed = store.remove_entry("key1");
        assert!(removed.is_some());
        assert_eq!(store.entry_count(), 0);
    }

    #[test]
    fn test_store_initialization_threshold() {
        let store = SessionMemoryStore::default();
        assert!(!store.has_met_initialization_threshold(5_000));
        assert!(store.has_met_initialization_threshold(10_000));
        assert!(store.has_met_initialization_threshold(15_000));
    }

    #[test]
    fn test_store_update_threshold() {
        let mut store = SessionMemoryStore::default();
        store.record_extraction_token_count(10_000);
        assert!(!store.has_met_update_threshold(12_000)); // only 2k growth
        assert!(store.has_met_update_threshold(16_000)); // 6k growth > 5k threshold
    }

    #[test]
    fn test_store_tool_call_threshold() {
        let mut store = SessionMemoryStore::default();
        store.record_tool_call();
        store.record_tool_call();
        assert!(!store.has_met_tool_call_threshold());
        store.record_tool_call();
        assert!(store.has_met_tool_call_threshold());
    }

    #[test]
    fn test_store_should_extract_below_init() {
        let mut store = SessionMemoryStore::default();
        assert!(!store.should_extract_memory(5_000, false));
    }

    #[test]
    fn test_store_should_extract_meets_init() {
        let mut store = SessionMemoryStore::default();
        // First call at 10k tokens: initializes but doesn't extract yet
        // (tokens_at_last_extraction is 0, growth = 10k > 5k, no tool calls, no tool calls in last turn)
        assert!(store.should_extract_memory(10_000, false));
    }

    #[test]
    fn test_store_extraction_state() {
        let mut store = SessionMemoryStore::default();
        store.mark_extraction_started();
        assert!(store.is_extraction_in_progress());
        store.mark_extraction_completed();
        assert!(!store.is_extraction_in_progress());
    }

    #[test]
    fn test_store_to_markdown() {
        let mut store = SessionMemoryStore::default();
        store.add_entry(
            MemoryEntry::new("goal_0", "Build a REST API")
                .with_category("goals"),
        );
        store.add_entry(
            MemoryEntry::new("file_main_rs", "src/main.rs")
                .with_category("file_reference"),
        );
        let md = store.to_markdown();
        assert!(md.contains("# Session Memory"));
        assert!(md.contains("Build a REST API"));
        assert!(md.contains("src/main.rs"));
    }

    #[test]
    fn test_store_to_markdown_empty() {
        let store = SessionMemoryStore::default();
        assert!(store.to_markdown().is_empty());
    }

    #[test]
    fn test_store_reset() {
        let mut store = SessionMemoryStore::default();
        store.mark_initialized();
        store.add_entry(MemoryEntry::new("k", "v"));
        store.record_tool_call();
        store.reset();
        assert!(!store.is_initialized());
        assert_eq!(store.entry_count(), 0);
    }

    #[test]
    fn test_store_last_summarized_message() {
        let mut store = SessionMemoryStore::default();
        assert!(store.last_summarized_message_id().is_none());
        store.set_last_summarized_message_id("msg-123");
        assert_eq!(store.last_summarized_message_id(), Some("msg-123"));
    }

    // --- extract_memories tests ---

    #[test]
    fn test_extract_memories_empty() {
        let entries = extract_memories(&[]);
        assert!(entries.is_empty());
    }

    #[test]
    fn test_extract_memories_goals() {
        let messages = vec![ConversationMessage::new(
            "user",
            "I want to build a REST API for user management.",
        )];
        let entries = extract_memories(&messages);
        assert!(!entries.is_empty());
        assert!(entries[0].value.contains("REST API"));
    }

    #[test]
    fn test_extract_memories_file_references() {
        let messages = vec![ConversationMessage::new(
            "user",
            "Please check src/main.rs and fix the bug.",
        )];
        let entries = extract_memories(&messages);
        let has_file = entries.iter().any(|e| e.value.contains("src/main.rs"));
        assert!(has_file);
    }

    #[test]
    fn test_extract_memories_preferences() {
        let messages = vec![ConversationMessage::new(
            "user",
            "I prefer using tabs instead of spaces.",
        )];
        let entries = extract_memories(&messages);
        assert!(!entries.is_empty());
    }

    #[test]
    fn test_extract_memories_skips_assistant() {
        let messages = vec![
            ConversationMessage::new("user", "I want to build something."),
            ConversationMessage::new("assistant", "I'll help you fix the issue in main.rs."),
        ];
        let entries = extract_memories(&messages);
        // Should only extract from user messages
        assert!(entries.iter().all(|e| !e.value.contains("assistant")));
    }

    // --- load_session_memory tests ---

    #[test]
    fn test_load_session_memory_empty() {
        let store = load_session_memory("").expect("should work");
        assert_eq!(store.entry_count(), 0);
    }

    #[test]
    fn test_load_session_memory_roundtrip() {
        let mut original = SessionMemoryStore::default();
        original.add_entry(
            MemoryEntry::new("goal_0", "Build API")
                .with_category("goals"),
        );
        original.add_entry(
            MemoryEntry::new("file_main_rs", "src/main.rs")
                .with_category("file_reference"),
        );

        let md = original.to_markdown();
        let loaded = load_session_memory(&md).expect("should load");
        assert_eq!(loaded.entry_count(), 2);
        assert_eq!(loaded.get_entry("goal_0").expect("entry").value, "Build API");
    }

    #[test]
    fn test_conversation_message_new() {
        let msg = ConversationMessage::new("user", "Hello");
        assert_eq!(msg.role, "user");
        assert_eq!(msg.content, "Hello");
        assert!(!msg.has_tool_calls);
    }

    #[test]
    fn test_conversation_message_with_tool_calls() {
        let msg = ConversationMessage::with_tool_calls("assistant", "Running tests");
        assert!(msg.has_tool_calls);
    }
}
