/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'rc-bg': {
          base: 'var(--color-bg-base)',
          surface: 'var(--color-bg-surface)',
          elevated: 'var(--color-bg-elevated)',
          sidebar: 'var(--color-bg-sidebar)',
          'activity-bar': 'var(--color-bg-activity-bar)',
          hover: 'var(--color-bg-hover)',
          active: 'var(--color-bg-active)',
          selected: 'var(--color-bg-selected)',
          chat: 'var(--color-bg-chat)',
          'chat-hover': 'var(--color-bg-chat-hover)',
          'user-bubble': 'var(--color-bg-user-bubble)',
          'user-solid': 'var(--color-bg-user-solid)',
          assistant: 'var(--color-bg-assistant)',
          'assistant-card': 'var(--color-bg-assistant-card)',
          code: 'var(--color-bg-code)',
          'code-header': 'var(--color-bg-code-header)',
          overlay: 'var(--color-bg-overlay)',
          // Legacy aliases
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          tertiary: 'var(--color-bg-tertiary)',
          input: 'var(--color-bg-surface)',
        },
        'rc-text': {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          inverse: 'var(--color-text-inverse)',
          link: 'var(--color-text-link)',
          'on-accent': 'var(--color-text-on-accent)',
        },
        'rc-border': {
          primary: 'var(--color-border-primary)',
          secondary: 'var(--color-border-secondary)',
          focus: 'var(--color-border-focus)',
          hover: 'var(--color-border-hover)',
        },
        'rc-accent': {
          primary: 'var(--color-accent-primary)',
          'primary-hover': 'var(--color-accent-primary-hover)',
          'primary-light': 'var(--color-accent-primary-light)',
          'primary-glow': 'var(--color-accent-primary-glow)',
          success: 'var(--color-accent-success)',
          'success-bg': 'var(--color-accent-success-bg)',
          'success-border': 'var(--color-accent-success-border)',
          warning: 'var(--color-accent-warning)',
          'warning-bg': 'var(--color-accent-warning-bg)',
          'warning-border': 'var(--color-accent-warning-border)',
          error: 'var(--color-accent-error)',
          'error-bg': 'var(--color-accent-error-bg)',
          'error-border': 'var(--color-accent-error-border)',
          info: 'var(--color-accent-info)',
          'info-bg': 'var(--color-accent-info-bg)',
          'info-border': 'var(--color-accent-info-border)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'xs': ['var(--text-xs)', { lineHeight: '1.5' }],
        'sm': ['var(--text-sm)', { lineHeight: '1.5' }],
        'base': ['var(--text-base)', { lineHeight: '1.5' }],
        'md': ['var(--text-md)', { lineHeight: '1.625' }],
        'lg': ['var(--text-lg)', { lineHeight: '1.5' }],
        'xl': ['var(--text-xl)', { lineHeight: '1.4' }],
        '2xl': ['var(--text-2xl)', { lineHeight: '1.35' }],
        '3xl': ['var(--text-3xl)', { lineHeight: '1.25' }],
      },
      spacing: {
        '13': '52px',
        '15': '60px',
        '18': '72px',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
        'glow-primary': 'var(--shadow-glow-primary)',
        'glow-success': 'var(--shadow-glow-success)',
        'glow-error': 'var(--shadow-glow-error)',
      },
      transitionDuration: {
        'fast': 'var(--transition-fast)',
        'normal': 'var(--transition-normal)',
        'slow': 'var(--transition-slow)',
      },
      zIndex: {
        'sidebar': 'var(--z-sidebar)',
        'header': 'var(--z-header)',
        'dropdown': 'var(--z-dropdown)',
        'overlay': 'var(--z-overlay)',
        'modal': 'var(--z-modal)',
        'toast': 'var(--z-toast)',
        'tooltip': 'var(--z-tooltip)',
      },
      width: {
        'activity-bar': 'var(--activity-bar-width)',
        'sidebar': 'var(--sidebar-width)',
      },
      height: {
        'status-bar': 'var(--status-bar-height)',
        'header': 'var(--header-height)',
      },
      maxWidth: {
        'chat': 'var(--chat-max-width)',
        'input': 'var(--input-max-width)',
        'sidebar': 'var(--sidebar-max-width)',
      },
      minWidth: {
        'sidebar': 'var(--sidebar-min-width)',
      },
      animation: {
        'fade-in': 'fadeIn var(--transition-normal) ease-out',
        'fade-in-up': 'fadeInUp var(--transition-slow) ease-out',
        'slide-in-right': 'slideInRight var(--transition-normal) ease-out',
        'scale-in': 'scaleIn var(--transition-slow) ease-out',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(-12px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
    },
  },
  plugins: [],
}